#!/bin/bash
set -o errexit
set -o nounset

INPUT=/bbx/input/biobox.yaml
OUTPUT=/bbx/output/bbx
TASK=$1

# Ensure the biobox.yml file is valid
validate-biobox-file --input ${INPUT} --schema /schema.yaml
mkdir -p ${OUTPUT}

# Parse the read locations from this file
READS=$(yaml2json < ${INPUT} \
        | jq --raw-output '.arguments[] | select(has("fastq")) | .fastq[].value | "-short \(.)"' \
        | tr '\n' ' ')


TMP_DIR=$(mktemp -d)

# Determine which process to run
CMD=$(egrep ^${TASK}: /Procfile | cut -f 2 -d ':')
if [[ -z ${CMD} ]]; then
  echo "Abort, no proc found for '${TASK}'."
  exit 1
fi
eval ${CMD}


# Run the given task
CMD=$(egrep ^${TASK}: /Taskfile | cut -f 2 -d ':')
if [[ -z ${CMD} ]]; then
  echo "Abort, no task found for '${TASK}'."
  exit 1
fi
eval ${CMD}

# unnoetig
#cp ${TMP_DIR}/contigs.fa ${OUTPUT}

cat << EOF > ${OUTPUT}/biobox.yaml
version: 0.9.0
arguments:
  - fasta:
    - id: megahit_contigs
      value: contigs.fa
      type: contigs
EOF

